# Imports

In [1]:
import torch

In [3]:
from self_attention import Self_Attention
from masked_attention import Masked_Attention
from multi_head_masked_attention_wrapper import Multi_Head_Masked_Attention_Wrapper
from multi_head_masked_attention import Multi_Head_Masked_Attention

# Input

In [4]:
inp=torch.rand(2,6,768)

In [5]:
inp

tensor([[[0.1916, 0.7405, 0.7503,  ..., 0.7236, 0.0530, 0.8050],
         [0.2949, 0.8872, 0.5758,  ..., 0.7028, 0.7118, 0.0871],
         [0.2161, 0.0823, 0.8335,  ..., 0.2517, 0.5548, 0.7502],
         [0.9243, 0.8506, 0.2784,  ..., 0.6992, 0.0462, 0.4746],
         [0.1685, 0.6929, 0.5765,  ..., 0.1538, 0.9458, 0.8240],
         [0.7380, 0.0055, 0.3136,  ..., 0.5400, 0.3458, 0.3324]],

        [[0.4060, 0.3556, 0.5793,  ..., 0.3916, 0.4675, 0.1001],
         [0.5890, 0.8107, 0.2625,  ..., 0.3975, 0.8985, 0.8409],
         [0.2129, 0.9901, 0.9728,  ..., 0.4470, 0.7938, 0.1730],
         [0.6968, 0.7835, 0.1916,  ..., 0.3030, 0.0355, 0.0364],
         [0.0383, 0.9165, 0.9016,  ..., 0.6136, 0.3981, 0.7778],
         [0.2982, 0.3707, 0.5799,  ..., 0.5849, 0.7073, 0.8661]]])

# Self Attention

In [6]:
self_attn=Self_Attention(dim_in=768,dim_out=768)

In [8]:
self_attn.parameters

<bound method Module.parameters of Self_Attention(
  (W_q): Linear(in_features=768, out_features=768, bias=False)
  (W_k): Linear(in_features=768, out_features=768, bias=False)
  (W_v): Linear(in_features=768, out_features=768, bias=False)
  (out_proj): Linear(in_features=768, out_features=768, bias=True)
)>

In [9]:
context_vec=self_attn(inp)

In [10]:
context_vec.shape

torch.Size([2, 6, 768])

In [12]:
context_vec

tensor([[[ 0.0351, -0.0131, -0.1072,  ...,  0.1542,  0.2004, -0.1522],
         [ 0.0352, -0.0136, -0.1066,  ...,  0.1538,  0.1996, -0.1519],
         [ 0.0347, -0.0133, -0.1067,  ...,  0.1544,  0.1997, -0.1529],
         [ 0.0347, -0.0123, -0.1065,  ...,  0.1560,  0.1986, -0.1523],
         [ 0.0346, -0.0149, -0.1070,  ...,  0.1516,  0.2016, -0.1541],
         [ 0.0340, -0.0129, -0.1069,  ...,  0.1554,  0.2006, -0.1536]],

        [[ 0.0198, -0.0473, -0.1095,  ...,  0.0926,  0.2031, -0.2127],
         [ 0.0193, -0.0480, -0.1095,  ...,  0.0918,  0.2020, -0.2114],
         [ 0.0188, -0.0461, -0.1103,  ...,  0.0915,  0.2021, -0.2124],
         [ 0.0184, -0.0466, -0.1093,  ...,  0.0939,  0.2042, -0.2125],
         [ 0.0197, -0.0468, -0.1084,  ...,  0.0941,  0.2034, -0.2133],
         [ 0.0174, -0.0464, -0.1097,  ...,  0.0935,  0.2045, -0.2117]]],
       grad_fn=<ViewBackward0>)

# Masked Attention

In [11]:
masked_attn=Masked_Attention(dim_in=768,dim_out=768)

In [13]:
masked_attn.parameters

<bound method Module.parameters of Masked_Attention(
  (W_q): Linear(in_features=768, out_features=768, bias=False)
  (W_k): Linear(in_features=768, out_features=768, bias=False)
  (W_v): Linear(in_features=768, out_features=768, bias=False)
  (out_proj): Linear(in_features=768, out_features=768, bias=True)
)>

In [14]:
context_vec=masked_attn(inp)

In [15]:
context_vec.shape

torch.Size([2, 6, 768])

In [16]:
context_vec

tensor([[[ 1.9132e-01, -1.0104e-01, -2.5400e-01,  ...,  2.3381e-01,
           3.5065e-01, -2.0010e-01],
         [ 1.2446e-01,  1.9800e-02, -2.7895e-01,  ...,  2.1606e-01,
           2.2818e-01, -2.2319e-01],
         [ 1.3344e-01,  3.7397e-02, -2.3063e-01,  ...,  1.9135e-01,
           2.5373e-01, -2.3243e-01],
         [ 1.2995e-01,  4.5183e-02, -2.3243e-01,  ...,  1.9575e-01,
           2.3549e-01, -2.2746e-01],
         [ 1.0950e-01,  4.3403e-02, -2.3501e-01,  ...,  1.6063e-01,
           2.0547e-01, -2.3051e-01],
         [ 9.4522e-02,  5.0979e-02, -2.6134e-01,  ...,  1.8110e-01,
           2.0414e-01, -2.3898e-01]],

        [[ 8.3500e-02,  8.1322e-02, -4.6296e-01,  ...,  2.9304e-02,
           9.2236e-02, -2.9848e-01],
         [ 1.4352e-01,  1.0037e-02, -2.7223e-01,  ...,  1.5669e-01,
           1.2278e-01, -2.3327e-01],
         [ 1.3982e-01,  4.9397e-02, -3.5783e-01,  ...,  1.8575e-01,
           1.6471e-01, -2.2376e-01],
         [ 1.1382e-01, -2.8647e-04, -3.3697e-01,  ...

# Multi Head Masked Attention Wrapper

### Here we used multiple masked attention head which are processed sequentially.
### The last dimension of input is not equal to the last dimension of output.

In [17]:
multi_head_masked_attn_wrapper=Multi_Head_Masked_Attention_Wrapper(
    dim_in=768,
    dim_out=768,
    n_heads=5
)

In [18]:
multi_head_masked_attn_wrapper.parameters

<bound method Module.parameters of Multi_Head_Masked_Attention_Wrapper(
  (attention_heads): ModuleList(
    (0-4): 5 x Masked_Attention(
      (W_q): Linear(in_features=768, out_features=768, bias=False)
      (W_k): Linear(in_features=768, out_features=768, bias=False)
      (W_v): Linear(in_features=768, out_features=768, bias=False)
      (out_proj): Linear(in_features=768, out_features=768, bias=True)
    )
  )
)>

In [19]:
context_vec=multi_head_masked_attn_wrapper(inp)

In [20]:
context_vec.shape

torch.Size([2, 6, 3840])

In [21]:
context_vec

tensor([[[-0.4206,  0.0285, -0.0523,  ...,  0.2326, -0.1499, -0.3078],
         [-0.4446,  0.0572, -0.0287,  ...,  0.3709, -0.1832, -0.2846],
         [-0.4687,  0.0740, -0.0490,  ...,  0.4027, -0.1873, -0.2849],
         [-0.4117,  0.0502, -0.0562,  ...,  0.4035, -0.1985, -0.3430],
         [-0.4198,  0.0467, -0.0379,  ...,  0.4444, -0.1750, -0.3377],
         [-0.4277,  0.0290, -0.0393,  ...,  0.4238, -0.1860, -0.3109]],

        [[-0.5077,  0.0111, -0.0432,  ...,  0.3237,  0.0403,  0.0012],
         [-0.5453,  0.0346, -0.0227,  ...,  0.3219, -0.0669, -0.1903],
         [-0.4395,  0.0727, -0.0532,  ...,  0.3109, -0.1448, -0.2098],
         [-0.3999,  0.0549, -0.0858,  ...,  0.2923, -0.1541, -0.2100],
         [-0.4060,  0.0401, -0.0905,  ...,  0.2691, -0.1702, -0.2349],
         [-0.4355,  0.0190, -0.0782,  ...,  0.2701, -0.1774, -0.2281]]],
       grad_fn=<CatBackward0>)

# Multi Head Masked Attention

### Here we break the query,key, value matrices and then provide it to the multiple heads.

### Here the last dimension of the input is same as the last dimension of the output.

In [22]:
multi_head_masked_attention=Multi_Head_Masked_Attention(
    dim_in=768,
    dim_out=768,
    n_heads=12,
    context_length=6
)

In [23]:
multi_head_masked_attention.parameters

<bound method Module.parameters of Multi_Head_Masked_Attention(
  (W_q): Linear(in_features=768, out_features=768, bias=False)
  (W_k): Linear(in_features=768, out_features=768, bias=False)
  (W_v): Linear(in_features=768, out_features=768, bias=False)
  (out_proj): Linear(in_features=768, out_features=768, bias=True)
)>

In [24]:
context_vec=multi_head_masked_attention(inp)

In [25]:
context_vec.shape

torch.Size([2, 6, 768])

In [26]:
context_vec

tensor([[[ 0.1288, -0.1447,  0.1463,  ...,  0.0699, -0.1754, -0.1706],
         [ 0.1326, -0.1822,  0.0636,  ...,  0.1282, -0.1867, -0.1366],
         [ 0.1645, -0.1870,  0.1172,  ...,  0.0973, -0.2251, -0.0817],
         [ 0.1533, -0.1830,  0.1570,  ...,  0.0824, -0.2532, -0.0982],
         [ 0.1955, -0.2071,  0.1655,  ...,  0.0613, -0.2616, -0.1018],
         [ 0.1619, -0.1866,  0.1508,  ...,  0.0320, -0.2948, -0.0872]],

        [[ 0.1958, -0.2388,  0.0247,  ...,  0.0216, -0.1469, -0.2091],
         [ 0.1006, -0.2556,  0.0295,  ..., -0.0085, -0.1231, -0.1131],
         [ 0.1073, -0.2796,  0.0111,  ..., -0.0025, -0.1610, -0.1544],
         [ 0.1146, -0.2023,  0.0488,  ...,  0.0220, -0.1437, -0.1785],
         [ 0.1169, -0.1912,  0.0777,  ...,  0.0390, -0.1633, -0.1537],
         [ 0.1429, -0.1964,  0.0897,  ...,  0.0301, -0.1816, -0.1461]]],
       grad_fn=<ViewBackward0>)